services:
  broker:
    # Theres nothing going on on kafka at this stage, but left it here for future use and testing 
    image: apache/kafka:latest
    hostname: kionas-broker
    container_name: kionas-broker
    networks:
      - warehouse_network
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kionas-broker:29092,PLAINTEXT_HOST://kionas-broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kionas-broker:29093
      KAFKA_LISTENERS: PLAINTEXT://kionas-broker:29092,CONTROLLER://kionas-broker:29093,PLAINTEXT_HOST://kionas-broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: mq.cluster.kionas
  devcontainer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    container_name: kionas-dev
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379      
    networks:
      - warehouse_network
    volumes:
      - ..:/workspace:cached
    tty: true
    stdin_open: true
    depends_on:
      - broker
      - redis
      - minio
  redis:
    image: redis:latest
    hostname: kionas-redis
    container_name: kionas-redis
    networks:
      - warehouse_network
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: password # You can change this, but remember to update the worker's REDIS_URL accordingly!
      REDIS_PORT: 6379
      REDIS_HOST: kionas-redis
      REDIS_URL: redis://kionas-redis:6379
      REDIS_DB: 0
      REDIS_CLUSTER_ENABLED: "false"
  minio:
    image: minio/minio:latest
    hostname: kionas-minio
    container_name: kionas-minio      
    networks:
      - warehouse_network
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword # You can change this, but remember to update the worker's AWS_SECRET_ACCESS_KEY accordingly!
      MINIO_REGION: us-east-1
      MINIO_BROWSER: "on"      
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address :9001
  
  consul:
    image: hashicorp/consul:latest
    hostname: kionas-consul
    container_name: kionas-consul
    networks:
      - warehouse_network
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0

  # Metastore service
  postgres:
    image: postgres:latest
    hostname: kionas-postgres
    container_name: kionas-postgres
    networks:
      - warehouse_network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kionas
      POSTGRES_PASSWORD: kionas
      POSTGRES_DB: kionas_metastore

  # Metastore container
  metastore:
    image: docker-devcontainer
    hostname: kionas-metastore
    container_name: kionas-metastore
    networks:
      - warehouse_network
    ports:
      - 50051:50051
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379     
    volumes:
      - ..:/workspace:cached
    depends_on:
      - postgres    
    # inifinite loop to keep the container running, replace with actual command when ready
    command: ["bash", "-c", "while true; do sleep 1000; done" ]

  # warehouse container
  warehouse:
    image: docker-devcontainer
    hostname: kionas-warehouse
    container_name: kionas-warehouse
    networks:
      - warehouse_network
    ports:
      - 8080:8080
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
    volumes:
      - ..:/workspace:cached
    depends_on:
      - metastore
      - minio
      - redis
    command: ["bash", "-c", "while true; do sleep 1000; done" ]

  # flight proxy container
  flight-proxy:
    image: docker-devcontainer
    hostname: kionas-flight-proxy
    container_name: kionas-flight-proxy
    networks:
      - warehouse_network
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      FLIGHT_PROXY_PORT: 443
      WORKER_FLIGHT_PORT: 50052
    volumes:
      - ..:/workspace:cached
    depends_on:
      - warehouse
    command: ["bash", "-c", "while true; do sleep 1000; done" ]

  # worker container
  worker1:
    image: docker-devcontainer
    hostname: kionas-worker1
    container_name: kionas-worker1
    networks:
      - warehouse_network
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      # storage endpoint and credentials for worker to access MinIO
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpassword # You can change this, but remember to update the MinIO container's MINIO_ROOT_PASSWORD accordingly!
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://kionas-minio:9000
      FLIGHT_PROXY_HOST: kionas-flight-proxy
      FLIGHT_PROXY_PORT: 443
    volumes:
      - ..:/workspace:cached
    depends_on:
      - warehouse
      
    command: ["bash", "-c", "while true; do sleep 1000; done" ]

  

networks:
  warehouse_network:
    external: true

volumes:
  minio_data:
  minio_config: