x-remote-infra-hosts: &remote_infra_hosts
  - "kionas-broker:192.168.0.15"
  - "kionas-redis:192.168.0.15"
  - "kionas-minio:192.168.0.15"
  - "kionas-consul:192.168.0.15"
  - "kionas-postgres:192.168.0.15"

services:

  builder:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    container_name: kionas-builder
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379      
    networks:
      - warehouse_network
    extra_hosts: *remote_infra_hosts
    volumes:
      - ..:/workspace:cached
    command: ["bash", "-c", "echo 'Builder container ready'" ]
  
  devcontainer:
    image: docker-builder
    container_name: kionas-dev
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379      
    networks:
      - warehouse_network
    extra_hosts: *remote_infra_hosts
    volumes:
      - ..:/workspace:cached
    tty: true
    stdin_open: true
   
  # Metastore container
  metastore:
    image: docker-builder
    hostname: kionas-metastore
    container_name: kionas-metastore
    networks:
      - warehouse_network
    extra_hosts: *remote_infra_hosts
    ports:
      - 50051:50051
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379     
    volumes:
      - ..:/workspace:cached     
    depends_on:
      builder:
        condition: service_completed_successfully
    # inifinite loop to keep the container running, replace with actual command when ready
    command: ["bash", "-c", "/workspace/docker-target/debug/metastore" ]

  # warehouse container
  warehouse:
    image: docker-builder
    hostname: kionas-warehouse
    container_name: kionas-warehouse
    networks:
      - warehouse_network
    extra_hosts: *remote_infra_hosts
    ports:
      - 8080:8080
      - 9091:9091
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      KIONAS_STAGE_EXCHANGE_RETENTION_SECONDS: 600
      KIONAS_QUERY_RESULT_RETENTION_SECONDS: 60
      KIONAS_CLEANUP_JOB_INTERVAL_SECONDS: 300
      KIONAS_TRANSACTION_STAGING_RETENTION_SECONDS: 600
      KIONAS_METRICS_PORT: 9091
    volumes:
      - ..:/workspace:cached
    depends_on:
      builder:
        condition: service_completed_successfully
      metastore:
        condition: service_started      
    command: ["bash", "-c", "/workspace/docker-target/debug/server" ]

  # flight proxy container
  flight-proxy:
    image: docker-builder
    hostname: kionas-flight-proxy
    container_name: kionas-flight-proxy
    networks:
      - warehouse_network
    extra_hosts: *remote_infra_hosts
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      FLIGHT_PROXY_PORT: 443
      WORKER_FLIGHT_PORT: 50052
    volumes:
      - ..:/workspace:cached
    depends_on:
      warehouse:
        condition: service_started
    command: ["bash", "-c", "/workspace/docker-target/debug/flight_proxy" ]

  # worker container
  worker1:
    image: docker-builder
    hostname: kionas-worker1
    container_name: kionas-worker1
    networks:
      - warehouse_network
    ports:
      - 9101:9101
    extra_hosts: *remote_infra_hosts
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      # storage endpoint and credentials for worker to access MinIO
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpassword # You can change this, but remember to update the MinIO container's MINIO_ROOT_PASSWORD accordingly!
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://kionas-minio:9000
      FLIGHT_PROXY_HOST: kionas-flight-proxy
      FLIGHT_PROXY_PORT: 443
      WORKER_POOL_NAME: compute_xl
      WORKER_FLIGHT_MAX_MESSAGE_BYTES: 33554432 # 32MB, adjust as needed
      KIONAS_WORKER_METRICS_PORT: 9101
    volumes:
      - ..:/workspace:cached
    depends_on:
      warehouse:
        condition: service_started
    command: ["bash", "-c", "/workspace/scripts/run_worker1.sh" ]

  worker2:
    image: docker-builder
    hostname: kionas-worker2
    container_name: kionas-worker2
    networks:
      - warehouse_network
    ports:
      - 9102:9102
    extra_hosts: *remote_infra_hosts
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      # storage endpoint and credentials for worker to access MinIO
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpassword # You can change this, but remember to update the MinIO container's MINIO_ROOT_PASSWORD accordingly!
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://kionas-minio:9000
      FLIGHT_PROXY_HOST: kionas-flight-proxy
      FLIGHT_PROXY_PORT: 443
      WORKER_POOL_NAME: compute_xl
      WORKER_FLIGHT_MAX_MESSAGE_BYTES: 33554432 # 32MB, adjust as needed
      KIONAS_WORKER_METRICS_PORT: 9102
    volumes:
      - ..:/workspace:cached
    depends_on:
      warehouse:
        condition: service_started
    command: ["bash", "-c", "/workspace/scripts/run_worker2.sh" ]

  worker3:
    image: docker-builder
    hostname: kionas-worker3
    container_name: kionas-worker3
    networks:
      - warehouse_network
    ports:
      - 9103:9103
    extra_hosts: *remote_infra_hosts
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      # storage endpoint and credentials for worker to access MinIO
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpassword # You can change this, but remember to update the MinIO container's MINIO_ROOT_PASSWORD accordingly!
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://kionas-minio:9000
      FLIGHT_PROXY_HOST: kionas-flight-proxy
      FLIGHT_PROXY_PORT: 443
      WORKER_POOL_NAME: compute_xl
      WORKER_FLIGHT_MAX_MESSAGE_BYTES: 33554432 # 32MB, adjust as needed
      KIONAS_WORKER_METRICS_PORT: 9103

    volumes:
      - ..:/workspace:cached
    depends_on:
      warehouse:
        condition: service_started
    command: ["bash", "-c", "/workspace/scripts/run_worker3.sh" ]

  worker4:
    image: docker-builder
    hostname: kionas-worker4
    container_name: kionas-worker4
    networks:
      - warehouse_network
    ports:
      - 9104:9104
    extra_hosts: *remote_infra_hosts
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: full
      KIONAS_HOME: /workspace
      CARGO_TARGET_DIR: /workspace/docker-target
      CONSUL_URL: http://kionas-consul:8500
      REDIS_URL: redis://kionas-redis:6379
      # storage endpoint and credentials for worker to access MinIO
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: rootpassword # You can change this, but remember to update the MinIO container's MINIO_ROOT_PASSWORD accordingly!
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://kionas-minio:9000
      FLIGHT_PROXY_HOST: kionas-flight-proxy
      FLIGHT_PROXY_PORT: 443
      WORKER_POOL_NAME: compute_xl
      WORKER_FLIGHT_MAX_MESSAGE_BYTES: 33554432 # 32MB, adjust as needed
      KIONAS_WORKER_METRICS_PORT: 9104
    volumes:
      - ..:/workspace:cached
    depends_on:
      warehouse:
        condition: service_started
    command: ["bash", "-c", "/workspace/scripts/run_worker4.sh" ]

  # UI backend container
  # ui-backend:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile.ui-backend
  #   hostname: kionas-ui-backend
  #   container_name: kionas-ui-backend
  #   networks:
  #     - warehouse_network
  #   extra_hosts: *remote_infra_hosts
  #   ports:
  #     - 8081:8081
  #   environment:
  #     RUST_LOG: debug
  #     RUST_BACKTRACE: full
  #     KIONAS_HOME: /workspace
  #     CARGO_TARGET_DIR: /workspace/docker-target
  #     REDIS_URL: redis://kionas-redis:6379
  #     UI_BACKEND_BIND: 0.0.0.0
  #     UI_BACKEND_PORT: 8081
  #   volumes:
  #     - ..:/workspace:cached
  #   depends_on:
  #     warehouse:
  #       condition: service_started
  #   # Run the pre-built binary directly (frontend already embedded)
  #   command: ["./ui_backend"]
    

  

networks:
  warehouse_network:
    external: true

volumes:
  minio_data:
  minio_config: