use crate::planner::error::PlannerError;
use crate::planner::physical_plan::{PhysicalExpr, PhysicalOperator, PhysicalPlan};

/// What: Validate whether a predicate expression belongs to the supported Phase 2 subset.
///
/// Inputs:
/// - `predicate`: Physical predicate expression from a filter operator.
///
/// Output:
/// - `Ok(())` when the predicate shape is currently supported.
/// - `Err(PlannerError::UnsupportedPredicate)` for deferred predicate families.
fn ensure_supported_predicate(predicate: &PhysicalExpr) -> Result<(), PlannerError> {
    let sql = match predicate {
        PhysicalExpr::Raw { sql } => sql.to_ascii_lowercase(),
        PhysicalExpr::ColumnRef { .. } => return Ok(()),
    };

    let unsupported = [
        (" between ", "BETWEEN"),
        (" in (", "IN list"),
        (" like ", "LIKE"),
        (" ilike ", "ILIKE"),
        (" exists", "EXISTS"),
        (" any ", "ANY"),
        (" all ", "ALL"),
        (" over (", "window function"),
    ];

    for (needle, label) in unsupported {
        if sql.contains(needle) {
            return Err(PlannerError::UnsupportedPredicate(label.to_string()));
        }
    }

    Ok(())
}

/// What: Validate Phase 2 physical plan invariants and capability limits.
///
/// Inputs:
/// - `plan`: Physical plan generated by logical-to-physical translation.
///
/// Output:
/// - `Ok(())` when the plan is valid for Phase 2 execution scope.
/// - `Err(PlannerError)` when unsupported operators or predicates are present.
pub fn validate_physical_plan(plan: &PhysicalPlan) -> Result<(), PlannerError> {
    if plan.operators.is_empty() {
        return Err(PlannerError::EmptyPhysicalPlan);
    }

    if !matches!(
        plan.operators.first(),
        Some(PhysicalOperator::TableScan { .. })
    ) {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "pipeline must start with table scan".to_string(),
        ));
    }

    if !matches!(plan.operators.last(), Some(PhysicalOperator::Materialize)) {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "pipeline must end with materialize".to_string(),
        ));
    }

    let projection_count = plan
        .operators
        .iter()
        .filter(|op| matches!(op, PhysicalOperator::Projection { .. }))
        .count();
    if projection_count != 1 {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "pipeline must contain exactly one projection".to_string(),
        ));
    }

    let sort_count = plan
        .operators
        .iter()
        .filter(|op| matches!(op, PhysicalOperator::Sort { .. }))
        .count();
    if sort_count > 1 {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "pipeline must contain at most one sort".to_string(),
        ));
    }

    let projection_index = plan
        .operators
        .iter()
        .position(|op| matches!(op, PhysicalOperator::Projection { .. }))
        .ok_or_else(|| {
            PlannerError::InvalidPhysicalPipeline(
                "pipeline must contain a projection operator".to_string(),
            )
        })?;

    if let Some(sort_index) = plan
        .operators
        .iter()
        .position(|op| matches!(op, PhysicalOperator::Sort { .. }))
        && sort_index < projection_index
    {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "sort must appear after projection".to_string(),
        ));
    }

    let limit_count = plan
        .operators
        .iter()
        .filter(|op| matches!(op, PhysicalOperator::Limit { .. }))
        .count();
    if limit_count > 1 {
        return Err(PlannerError::InvalidPhysicalPipeline(
            "pipeline must contain at most one limit".to_string(),
        ));
    }

    if let Some(limit_index) = plan
        .operators
        .iter()
        .position(|op| matches!(op, PhysicalOperator::Limit { .. }))
    {
        if limit_index < projection_index {
            return Err(PlannerError::InvalidPhysicalPipeline(
                "limit must appear after projection".to_string(),
            ));
        }

        if let Some(sort_index) = plan
            .operators
            .iter()
            .position(|op| matches!(op, PhysicalOperator::Sort { .. }))
            && limit_index < sort_index
        {
            return Err(PlannerError::InvalidPhysicalPipeline(
                "limit must appear after sort".to_string(),
            ));
        }
    }

    for op in &plan.operators {
        match op {
            PhysicalOperator::Filter { predicate } => ensure_supported_predicate(predicate)?,
            PhysicalOperator::TableScan { .. }
            | PhysicalOperator::Projection { .. }
            | PhysicalOperator::Materialize => {}
            PhysicalOperator::Sort { keys } => {
                if keys.is_empty() {
                    return Err(PlannerError::InvalidPhysicalPipeline(
                        "sort operator must include at least one key".to_string(),
                    ));
                }
            }
            PhysicalOperator::Limit { spec: _ } => {}
            PhysicalOperator::HashJoin { .. } => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "HashJoin".to_string(),
                ));
            }
            PhysicalOperator::NestedLoopJoin => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "NestedLoopJoin".to_string(),
                ));
            }
            PhysicalOperator::AggregatePartial => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "AggregatePartial".to_string(),
                ));
            }
            PhysicalOperator::AggregateFinal => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "AggregateFinal".to_string(),
                ));
            }
            PhysicalOperator::ExchangeShuffle { .. } => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "ExchangeShuffle".to_string(),
                ));
            }
            PhysicalOperator::ExchangeBroadcast => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "ExchangeBroadcast".to_string(),
                ));
            }
            PhysicalOperator::Repartition => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "Repartition".to_string(),
                ));
            }
            PhysicalOperator::Union => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "Union".to_string(),
                ));
            }
            PhysicalOperator::Values => {
                return Err(PlannerError::UnsupportedPhysicalOperator(
                    "Values".to_string(),
                ));
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_physical_plan;
    use crate::planner::error::PlannerError;
    use crate::planner::logical_plan::LogicalRelation;
    use crate::planner::physical_plan::{
        PhysicalExpr, PhysicalLimitSpec, PhysicalOperator, PhysicalPlan, PhysicalSortExpr,
    };

    fn base_relation() -> LogicalRelation {
        LogicalRelation {
            database: "sales".to_string(),
            schema: "public".to_string(),
            table: "users".to_string(),
        }
    }

    fn base_valid_plan() -> PhysicalPlan {
        PhysicalPlan {
            operators: vec![
                PhysicalOperator::TableScan {
                    relation: base_relation(),
                },
                PhysicalOperator::Projection {
                    expressions: vec![PhysicalExpr::Raw {
                        sql: "id".to_string(),
                    }],
                },
                PhysicalOperator::Materialize,
            ],
            sql: "SELECT id FROM users".to_string(),
        }
    }

    #[test]
    fn rejects_each_deferred_operator() {
        let cases = vec![
            (
                PhysicalOperator::HashJoin { on: Vec::new() },
                "HashJoin".to_string(),
            ),
            (
                PhysicalOperator::NestedLoopJoin,
                "NestedLoopJoin".to_string(),
            ),
            (
                PhysicalOperator::AggregatePartial,
                "AggregatePartial".to_string(),
            ),
            (
                PhysicalOperator::AggregateFinal,
                "AggregateFinal".to_string(),
            ),
            (
                PhysicalOperator::ExchangeShuffle {
                    keys: vec!["id".to_string()],
                },
                "ExchangeShuffle".to_string(),
            ),
            (
                PhysicalOperator::ExchangeBroadcast,
                "ExchangeBroadcast".to_string(),
            ),
            (PhysicalOperator::Repartition, "Repartition".to_string()),
            (PhysicalOperator::Union, "Union".to_string()),
            (PhysicalOperator::Values, "Values".to_string()),
        ];

        for (deferred_op, expected_name) in cases {
            let mut plan = base_valid_plan();
            plan.operators.insert(1, deferred_op);

            let err = validate_physical_plan(&plan)
                .expect_err("must reject deferred operator from capability matrix");
            assert_eq!(
                err,
                PlannerError::UnsupportedPhysicalOperator(expected_name),
                "unexpected error for deferred operator"
            );
        }
    }

    #[test]
    fn rejects_deferred_predicate_shapes() {
        let cases = vec![
            ("age BETWEEN 1 AND 10".to_string(), "BETWEEN".to_string()),
            ("country IN ('us', 'br')".to_string(), "IN list".to_string()),
            ("name LIKE 'a%'".to_string(), "LIKE".to_string()),
            ("name ILIKE 'A%'".to_string(), "ILIKE".to_string()),
            (
                "EXISTS (SELECT 1 FROM sales.public.users)".to_string(),
                "EXISTS".to_string(),
            ),
            ("score = ANY (ARRAY[1,2])".to_string(), "ANY".to_string()),
            ("score = ALL (ARRAY[1,2])".to_string(), "ALL".to_string()),
            (
                "row_number() OVER (PARTITION BY id) > 1".to_string(),
                "window function".to_string(),
            ),
        ];

        for (predicate_sql, expected) in cases {
            let mut plan = base_valid_plan();
            plan.operators.insert(
                1,
                PhysicalOperator::Filter {
                    predicate: PhysicalExpr::Raw { sql: predicate_sql },
                },
            );

            let err = validate_physical_plan(&plan)
                .expect_err("must reject deferred predicate from capability matrix");
            assert_eq!(err, PlannerError::UnsupportedPredicate(expected));
        }
    }

    #[test]
    fn accepts_supported_filter_predicate() {
        let mut plan = base_valid_plan();
        plan.operators.insert(
            1,
            PhysicalOperator::Filter {
                predicate: PhysicalExpr::Raw {
                    sql: "active = true".to_string(),
                },
            },
        );

        validate_physical_plan(&plan).expect("must accept supported predicate");
    }

    #[test]
    fn accepts_sort_when_keys_are_present() {
        let mut plan = base_valid_plan();
        plan.operators.insert(
            2,
            PhysicalOperator::Sort {
                keys: vec![PhysicalSortExpr {
                    expression: PhysicalExpr::Raw {
                        sql: "id".to_string(),
                    },
                    ascending: true,
                }],
            },
        );

        validate_physical_plan(&plan).expect("sort should be accepted in this phase");
    }

    #[test]
    fn accepts_limit_after_sort() {
        let mut plan = base_valid_plan();
        plan.operators.insert(
            2,
            PhysicalOperator::Sort {
                keys: vec![PhysicalSortExpr {
                    expression: PhysicalExpr::Raw {
                        sql: "id".to_string(),
                    },
                    ascending: true,
                }],
            },
        );
        plan.operators.insert(
            3,
            PhysicalOperator::Limit {
                spec: PhysicalLimitSpec {
                    count: 5,
                    offset: 2,
                },
            },
        );

        validate_physical_plan(&plan).expect("limit should be accepted in this phase");
    }

    #[test]
    fn rejects_limit_before_sort() {
        let mut plan = base_valid_plan();
        plan.operators.insert(
            2,
            PhysicalOperator::Limit {
                spec: PhysicalLimitSpec {
                    count: 5,
                    offset: 0,
                },
            },
        );
        plan.operators.insert(
            3,
            PhysicalOperator::Sort {
                keys: vec![PhysicalSortExpr {
                    expression: PhysicalExpr::Raw {
                        sql: "id".to_string(),
                    },
                    ascending: true,
                }],
            },
        );

        let err = validate_physical_plan(&plan).expect_err("limit before sort must be rejected");
        assert_eq!(
            err,
            PlannerError::InvalidPhysicalPipeline("limit must appear after sort".to_string())
        );
    }
}
