use crate::planner::error::PlannerError;
use crate::planner::logical_plan::LogicalPlan;
use crate::sql::constraints::TableConstraintContract;

/// What: Validate Phase 1 logical plan invariants.
///
/// Inputs:
/// - `plan`: Logical plan generated by translation.
///
/// Output:
/// - `Ok(())` when validation passes.
/// - `Err(PlannerError)` when required plan sections are missing.
///
/// Details:
/// - Validation is intentionally strict and deterministic to keep planner output
///   stable for payload serialization and tests.
pub fn validate_logical_plan(plan: &LogicalPlan) -> Result<(), PlannerError> {
    if plan.relation.database.trim().is_empty()
        || plan.relation.schema.trim().is_empty()
        || plan.relation.table.trim().is_empty()
    {
        return Err(PlannerError::EmptyRelation);
    }

    if plan.projection.expressions.is_empty() {
        return Err(PlannerError::EmptyProjection);
    }

    for join in &plan.joins {
        if join.right_relation.database.trim().is_empty()
            || join.right_relation.schema.trim().is_empty()
            || join.right_relation.table.trim().is_empty()
        {
            return Err(PlannerError::EmptyRelation);
        }

        if join.keys.is_empty() {
            return Err(PlannerError::InvalidLogicalPlan(
                "join must include at least one key".to_string(),
            ));
        }
    }

    if !plan.grouping_keys.is_empty() && plan.aggregates.is_empty() {
        return Err(PlannerError::InvalidLogicalPlan(
            "GROUP BY requires at least one aggregate expression in projection".to_string(),
        ));
    }

    if !plan.aggregates.is_empty() {
        for aggregate in &plan.aggregates {
            if aggregate.output_name.trim().is_empty() {
                return Err(PlannerError::InvalidLogicalPlan(
                    "aggregate output name cannot be empty".to_string(),
                ));
            }
        }
    }

    Ok(())
}

/// What: Validate normalized table-constraint contract invariants.
///
/// Inputs:
/// - `contract`: Constraint contract created from CREATE TABLE semantics.
///
/// Output:
/// - `Ok(())` when constraint contract is coherent.
/// - `Err(PlannerError)` when duplicate/empty constraint fields are found.
///
/// Details:
/// - Validation is strict to preserve deterministic metadata handoff.
pub fn validate_constraint_contract(
    contract: &TableConstraintContract,
) -> Result<(), PlannerError> {
    if contract.columns.is_empty() {
        return Err(PlannerError::InvalidLogicalPlan(
            "constraint contract must include at least one column".to_string(),
        ));
    }

    let mut seen = std::collections::HashSet::new();
    for column in &contract.columns {
        let name = column.column.trim();
        if name.is_empty() {
            return Err(PlannerError::InvalidLogicalPlan(
                "constraint contract column name cannot be empty".to_string(),
            ));
        }

        let canonical = name.to_ascii_lowercase();
        if !seen.insert(canonical.clone()) {
            return Err(PlannerError::InvalidLogicalPlan(format!(
                "constraint contract has duplicate column entry: {}",
                canonical
            )));
        }

        if column.not_null && column.nullable {
            return Err(PlannerError::InvalidLogicalPlan(format!(
                "constraint contract column '{}' cannot be nullable and NOT NULL simultaneously",
                name
            )));
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_logical_plan;
    use crate::planner::error::PlannerError;
    use crate::planner::logical_plan::{LogicalPlan, LogicalProjection, LogicalRelation};

    #[test]
    fn rejects_empty_projection() {
        let plan = LogicalPlan {
            relation: LogicalRelation {
                database: "sales".to_string(),
                schema: "public".to_string(),
                table: "users".to_string(),
            },
            projection: LogicalProjection {
                expressions: Vec::new(),
            },
            selection: None,
            joins: Vec::new(),
            grouping_keys: Vec::new(),
            aggregates: Vec::new(),
            order_by: Vec::new(),
            limit: None,
            offset: None,
            sql: "SELECT FROM sales.public.users".to_string(),
        };

        let err = validate_logical_plan(&plan).expect_err("should reject empty projection");
        assert_eq!(err, PlannerError::EmptyProjection);
    }
}
