use crate::planner::error::PlannerError;
use crate::planner::logical_plan::LogicalPlan;

/// What: Validate Phase 1 logical plan invariants.
///
/// Inputs:
/// - `plan`: Logical plan generated by translation.
///
/// Output:
/// - `Ok(())` when validation passes.
/// - `Err(PlannerError)` when required plan sections are missing.
///
/// Details:
/// - Validation is intentionally strict and deterministic to keep planner output
///   stable for payload serialization and tests.
pub fn validate_logical_plan(plan: &LogicalPlan) -> Result<(), PlannerError> {
    if plan.relation.database.trim().is_empty()
        || plan.relation.schema.trim().is_empty()
        || plan.relation.table.trim().is_empty()
    {
        return Err(PlannerError::EmptyRelation);
    }

    if plan.projection.expressions.is_empty() {
        return Err(PlannerError::EmptyProjection);
    }

    for join in &plan.joins {
        if join.right_relation.database.trim().is_empty()
            || join.right_relation.schema.trim().is_empty()
            || join.right_relation.table.trim().is_empty()
        {
            return Err(PlannerError::EmptyRelation);
        }

        if join.keys.is_empty() {
            return Err(PlannerError::InvalidLogicalPlan(
                "join must include at least one key".to_string(),
            ));
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_logical_plan;
    use crate::planner::error::PlannerError;
    use crate::planner::logical_plan::{LogicalPlan, LogicalProjection, LogicalRelation};

    #[test]
    fn rejects_empty_projection() {
        let plan = LogicalPlan {
            relation: LogicalRelation {
                database: "sales".to_string(),
                schema: "public".to_string(),
                table: "users".to_string(),
            },
            projection: LogicalProjection {
                expressions: Vec::new(),
            },
            selection: None,
            joins: Vec::new(),
            order_by: Vec::new(),
            limit: None,
            offset: None,
            sql: "SELECT FROM sales.public.users".to_string(),
        };

        let err = validate_logical_plan(&plan).expect_err("should reject empty projection");
        assert_eq!(err, PlannerError::EmptyProjection);
    }
}
